<?php

function playwall_menu() {
  $items['hackday'] = array(
    'title' => 'Trending Stories',
    'page callback' => '_playwall_trending',
    'access callback' => TRUE,
  );

  $items['hackday/ajax'] = array(
    'title' => 'Trending Stories',
    'page callback' => '_hackday_trending_getmore',
    'access callback' => TRUE,
  );
  $items['hackday/addpoints'] = array(
    'title' => 'Add Points',
    'page callback' => 'hackday_add_user_points',
    'access callback' => TRUE,
  );
  $items['hackday/showpoints'] = array(
    'title' => 'Add Points',
    'page callback' => 'hackday_show_user_points',
    'access callback' => TRUE,
  );

  return $items;
}

function hackday_show_user_points() {
  $query = db_query('SELECT * FROM {points} p WHERE p.email = :email', array(':email' => $_POST['email']));
  $result = $query->fetchAll();
  if(!empty($result)) {
    echo $result[0]->points;
    exit;
  }
}

function hackday_add_user_points() {
  $query = db_query('SELECT * FROM {points} p WHERE p.email = :email', array(':email' => $_POST['email']));
  $result = $query->fetchAll();
  if(!empty($result)) {
    $num_updated = db_update('points') // Table name no longer needs {}
      ->fields(array(
        'points' => $result[0]->points + 1,
      ))
      ->condition('email', $result[0]->email, '=')
      ->execute();
  }
  else {
    $id = db_insert('points') // Table name no longer needs {}
    ->fields(array(
      'email' => $_POST['email'],
      'fname' => $_POST['firstName'],
      'points' => $_POST['points'],
    ))
    ->execute();
  }
  exit;
}

function _playwall_trending() {
  drupal_add_js(drupal_get_path('module', 'playwall') . '/js/jquery.snap-puzzle.js', array('scope'=>'footer'));
  drupal_add_js(drupal_get_path('module', 'playwall') . '/js/playwall.js', array('scope'=>'footer'));
  drupal_add_js("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js", "external");
  drupal_add_js("//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js", "external");
  drupal_add_js("//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js", "external");
  drupal_add_js("//cdn.gigya.com/JS/socialize.js?apikey=3_mK2cmEzLkzhqe4MUrtPncxbv4wKsYAhsew0iVwhVUls3c_Jx_HLX434jAVpq5M_W", "external");

  drupal_add_css("//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/ui-darkness/jquery-ui.min.css", "external");
  drupal_add_css("//fonts.googleapis.com/css?family=Source+Sans+Pro:300", "external");
  drupal_add_css("//yui.yahooapis.com/pure/0.5.0/pure-min.css", "external");
  drupal_add_css("//yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css", "external");

  $trending_url = "http://api.onebot.timeinc.com/feeds/timeinc/all.json";
  $json = file_get_contents($trending_url);
  $data = json_decode($json);
  $vars['trending'] = $data;
  $html = theme('playwall', $vars);
  return $html;
}

function playwall_theme() {
  return array(
    'playwall' => array(
      'variables' => array('items' => NULL),
      'template' => 'playwall',
    ),
  );
}
function beauty_theme_preprocess_playwall(&$variables) {
  foreach ($variables['trending']->trending as &$value) {
    $value->image->thumbnail = theme('imagecache_external', array('path' => $value->image->thumbnail, 'style_name'=> 'large'));
    $value->read_more = l("Read More", 'javascript:void(0);', array('external'=>true, 'attributes' => array("class" => array('dialogify'))));
    $tags=$value->tags;
    if ( isset($tags[1]->tag)) {
      $image_url=_search_web_image($tags[1]->tag);
      $value->puzzle_image = $image_url;
    }
    else {
      $value->puzzle_image = 'http://img2-2.timeinc.net/people/i/2014/news/140908/full-house-1024.jpg';
    }
  }
}

function _search_web_image($img) {

  $url = "https://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=".urlencode($img);
  //sendRequest
  //note how referer is set manually
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  //curl_setopt($ch, CURLOPT_REFERER, 'people.com');
  $body = curl_exec($ch);
  curl_close($ch);
  //now, process the JSON string. and return image.
  $json = json_decode($body);
  return $json->responseData->results[0]->url;
}

function _hackday_trending_getmore() {

  $readability_token = "&token=30d037eff9e89aa37afd552ec2b486e371a0a21b";
  $readability_url = "https://www.readability.com/api/content/v1/parser";
  $page = $_POST['url'];
  $brand = strtolower($_POST['brand']);
  $url = $readability_url . "?url=" . $page . $readability_token;
  $result = drupal_http_request($url);
  $data = json_decode($result->data, TRUE);

  switch ($brand) {
    case "people.com":
      $doc = new DOMDocument();
      $doc->loadHTML($data['content']);
      $output = $doc->getElementById('articleBody')->nodeValue;
      break;

    default:
      $output = $data['content'];
      break;
  }

  echo "<pre>" . $output . "</pre>";
}
